spring:
  cloud:
    config:
      server:
        git:
          uri:
            native: ssh://localhost/config
            clone-on-start: true
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
server:
  port: 8888
security:
  basic: enabled
  user:
      name: leomn138
      password: leomn138
      role: USER