server:
  port: 8080

recommendations:
  scheduling:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:52000/BookRecommendationSystem
    username: root
    password: leomn138
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
spark:
  environment: local
  applicationName: BookRecommendationSystem
  model:
    train:
      rank: 10
      interactionsNumber: 10
      lambda: 0.01
      cron: 0 0 * ? * *
